_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

#ToxSatelliteBundle:
#    resource: "@ToxSatelliteBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#ToxPlaceBundle:
#    resource: "@ToxPlaceBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
ToxParserBundle:
    resource: "@ToxParserBundle/Controller/"
    type:     annotation
    prefix:   /
ToxSatelliteBundle:
    resource: "@ToxSatelliteBundle/Controller/"
    type:     annotation
    prefix:
ToxPlaceBundle:
    resource: "@ToxPlaceBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
