Tox\ParserBundle\Entity\RawText:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    content:
      type: text
      length: 10000
      nullable: false
  manyToOne:
    Theme:
      targetEntity: Tox\SatelliteBundle\Entity\Theme
      inversedBy: RawPages
      joinColumns: { theme_id: { referencedColumnName: id } }
    Source:
      targetEntity: Tox\ParserBundle\Entity\Source
      inversedBy: RawPages
      joinColumns: { Source_id: { referencedColumnName: id } }
